occ_active_sensor:
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  sensorNamePattern: nameLeaf
  interfaces:
    org.open_power.OCC.Status:
      OccActive:
        Offsets:
          0x00:
            type: "bool"
            assert: "false"
            deassert: "true"
          0x01:
            type: "bool"
            assert: "true"
            deassert: "false"
