0x03:
  sensorType: 0x0F
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: eventdata2
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.State.Boot.Progress:
      BootProgress:
        Offsets:
          0x13:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSStart
          0x00:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
          0x01:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.MemoryInit
          0x07:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.PCIInit
          0x14:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.MotherboardInit
          0x03:
            type: string
            set: xyz.openbmc_project.State.Boot.Progress.ProgressStages.SecondaryProcInit
0x05:
  sensorType: 0x1F
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.State.OperatingSystem.Status:
      OperatingSystemState:
        Offsets:
          0x02:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.PXEBoot
            type: string
          0x06:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.BootComplete
            type: string
          0x04:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.CDROMBoot
            type: string
          0x01:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.CBoot
            type: string
          0x03:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.DiagBoot
            type: string
          0x05:
            assert: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.ROMBoot
            type: string
0x07:
  sensorType: 0xC3
  path: /xyz/openbmc_project/state/host0
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingAssertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.Control.Boot.RebootAttempts:
      AttemptsLeft:
        Offsets:
          0xFF:
            type: uint32_t
0x21:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu0
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
0x6A:
  sensorType: 0x07
  path: /org/open_power/control/occ0
  sensorReadingType: 0x09
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    org.open_power.OCC.Status:
      OccActive:
        Offsets:
          0x00:
            assert: false
            deassert: true
            type: bool
          0x01:
            assert: true
            deassert: false
            type: bool
0x71:
  sensorType: 0x07
  path: /system/chassis/motherboard/cpu1
  sensorReadingType: 0x6F
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.State.Decorator.OperationalStatus:
      Functional:
        Prereqs:
          0x07:
            assert: true
            deassert: false
            type: bool
        Offsets:
          0x08:
            assert: false
            deassert: true
            type: bool
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x07:
            assert: true
            deassert: false
            type: bool
0xBA:
  sensorType: 0x07
  path: /org/open_power/control/occ1
  sensorReadingType: 0x09
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    org.open_power.OCC.Status:
      OccActive:
        Offsets:
          0x00:
            assert: false
            deassert: true
            type: bool
          0x01:
            assert: true
            deassert: false
            type: bool
0xFC:
  sensorType: 0xCD
  path: /system/chassis/pcie_card_e2b
  sensorReadingType: 0x03
  serviceInterface: xyz.openbmc_project.Inventory.Manager
  readingType: assertion
  mutability: Mutability::Write|Mutability::Read
  interfaces:
    xyz.openbmc_project.Inventory.Item:
      Present:
        Offsets:
          0x01:
            assert: true
            deassert: false
            type: bool
